basePath=https://10.41.4.83:8443
Authenticate_Endpoint=/aeengine/rest/authenticate
UserbasePath=https://10.41.4.83:8443
UserbaseEndpoint=/aeengine/rest/tenants/BMC/users/1349
Usergroup_Endpoint=https://10.41.4.83:8443/aeengine/rest/tenants/BMC/groups